x-base-service: &base-service
  restart: unless-stopped
  build:
    context: .
    target: development
    args:
      USER_ID: ${UID:-1000}
      GROUP_ID: ${GID:-1000}
      PHP_VERSION: 8.3
  environment:
    PHP_MEMORY_LIMIT: "512M"
    REVERB_APP_ID: ${REVERB_APP_ID}
    REVERB_APP_KEY: ${REVERB_APP_KEY}
    REVERB_APP_SECRET: ${REVERB_APP_SECRET}
    REVERB_HOST: ${REVERB_HOST}
    REVERB_PORT: ${REVERB_PORT}
    REVERB_SCHEME: ${REVERB_SCHEME}
    REVERB_SERVER_HOST: ${REVERB_SERVER_HOST}
    REVERB_SERVER_PORT: ${REVERB_SERVER_PORT}
    REVERB_LOG_LEVEL: ${REVERB_LOG_LEVEL}
  volumes:
    - .:/var/www/html:cached
  networks:
    - nginx-proxy-manager-network

services:
  laravel:
    <<: *base-service
    container_name: grd-tsui
    working_dir: /var/www/html
    ports:
      - 8080:8080
      - 5173:5173
      - 8000:8000
      - 6001:6001
    # healthcheck:
    #   test: ["CMD", "test", "-f", "/var/www/html/vendor/autoload.php"]
    #   interval: 5s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s

  task:
    <<: *base-service
    container_name: grd-tsui-task
    command: ["php", "/var/www/html/artisan", "schedule:work"]
    stop_signal: SIGTERM
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck-schedule"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      laravel:
        condition: service_healthy

  queue:
    <<: *base-service
    container_name: grd-tsui-queue
    command: ["php", "/var/www/html/artisan", "queue:work", "--tries=3"]
    stop_signal: SIGTERM
    healthcheck:
      test: ["CMD", "healthcheck-queue"]
      start_period: 10s
    depends_on:
      laravel:
        condition: service_healthy

  # reverb:
  #   <<: *base-service
  #   container_name: grd-tsui-reverb
  #   # command: ["php", "/var/www/html/artisan", "--port=8000", "reverb:start"]
  #   command: ["php", "/var/www/html/artisan", "reverb:start", "--host=0.0.0.0", "--port=6001"]
  #   stop_signal: SIGTERM # Set this for graceful shutdown if you're using fpm-apache or fpm-nginx
  #   ports:
  #     - 8000:8000
  #     - 6001:6001
  #   healthcheck:
  #     # This is our native healthcheck script for Reverb
  #     test: ["CMD", "healthcheck-reverb"]
  #     start_period: 10s

networks:
  nginx-proxy-manager-network:
    external: true
